[2024-09-25T02:24:34.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T02:24:34.691+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T02:24:34.699+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T02:24:34.700+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T02:24:34.723+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-23 00:00:00+00:00
[2024-09-25T02:24:34.729+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T02:24:34.731+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-09-25T02:24:34.729+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpic6cyzp7']
[2024-09-25T02:24:34.731+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask scrape
[2024-09-25T02:24:34.806+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [running]> on host 3d91334001db
[2024-09-25T02:24:34.912+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-09-25T02:24:34.913+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T02:24:34.925+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T02:24:34.926+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello']
[2024-09-25T02:24:34.933+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T02:24:34.933+0000] {subprocess.py:93} INFO - hello
[2024-09-25T02:24:34.933+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-25T02:24:34.934+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T02:24:34.949+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240923T000000, start_date=20240925T022434, end_date=20240925T022434
[2024-09-25T02:24:35.001+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-25T02:24:35.019+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T02:24:35.023+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-25T19:17:33.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:17:33.650+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:17:33.656+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:17:33.657+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:17:33.664+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-23 00:00:00+00:00
[2024-09-25T19:17:33.668+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:17:33.672+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-09-25T19:17:33.671+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9gqg9r6x']
[2024-09-25T19:17:33.674+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask scrape
[2024-09-25T19:17:33.702+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [running]> on host 3e7c0ef0cbf3
[2024-09-25T19:17:33.749+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-09-25T19:17:33.750+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:17:33.763+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:17:33.764+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python tasks/testcode.py']
[2024-09-25T19:17:33.770+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:17:33.790+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpksneubxw/tasks/testcode.py': [Errno 2] No such file or directory
[2024-09-25T19:17:33.792+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T19:17:33.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:17:33.798+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T19:17:33.801+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240923T000000, start_date=20240925T191733, end_date=20240925T191733
[2024-09-25T19:17:33.809+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 68)
[2024-09-25T19:17:33.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:17:33.859+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:17:33.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-25T19:23:00.075+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:23:00.089+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:23:00.094+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:23:00.095+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:23:00.104+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-23 00:00:00+00:00
[2024-09-25T19:23:00.109+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:23:00.110+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2024-09-25T19:23:00.110+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpae8tqm4o']
[2024-09-25T19:23:00.113+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask scrape
[2024-09-25T19:23:00.153+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [running]> on host 8445e15c9faf
[2024-09-25T19:23:00.209+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-09-25T19:23:00.210+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:23:00.224+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:23:00.225+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../tasks/testcode.py']
[2024-09-25T19:23:00.231+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:23:00.255+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpofbwx1l6/../tasks/testcode.py': [Errno 2] No such file or directory
[2024-09-25T19:23:00.258+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-25T19:23:00.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:23:00.265+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-25T19:23:00.268+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240923T000000, start_date=20240925T192300, end_date=20240925T192300
[2024-09-25T19:23:00.276+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task scrape (Bash command failed. The command returned a non-zero exit code 2.; 87)
[2024-09-25T19:23:00.294+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:23:00.307+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:23:00.308+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-25T19:37:53.142+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:37:53.154+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:37:53.160+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-09-25T19:37:53.163+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:37:53.185+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-23 00:00:00+00:00
[2024-09-25T19:37:53.201+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:37:53.202+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-09-25T19:37:53.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5zuyba5f']
[2024-09-25T19:37:53.204+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask scrape
[2024-09-25T19:37:53.260+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape scheduled__2024-09-23T00:00:00+00:00 [running]> on host a5905166bf2e
[2024-09-25T19:37:53.348+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-09-25T19:37:53.350+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:37:53.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:37:53.357+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T19:37:53.364+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:37:54.650+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-25T19:37:54.650+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 7, in <module>
[2024-09-25T19:37:54.652+0000] {subprocess.py:93} INFO -     from pipelineActions import *
[2024-09-25T19:37:54.652+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/pipelineActions.py", line 9, in <module>
[2024-09-25T19:37:54.652+0000] {subprocess.py:93} INFO -     access = config.get('aws_boto_credentials', 'access_key')
[2024-09-25T19:37:54.652+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-25T19:37:54.652+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 759, in get
[2024-09-25T19:37:54.653+0000] {subprocess.py:93} INFO -     d = self._unify_values(section, vars)
[2024-09-25T19:37:54.653+0000] {subprocess.py:93} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-25T19:37:54.653+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/configparser.py", line 1130, in _unify_values
[2024-09-25T19:37:54.653+0000] {subprocess.py:93} INFO -     raise NoSectionError(section) from None
[2024-09-25T19:37:54.653+0000] {subprocess.py:93} INFO - configparser.NoSectionError: No section: 'aws_boto_credentials'
[2024-09-25T19:37:54.763+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-25T19:37:54.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:37:54.776+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T19:37:54.781+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240923T000000, start_date=20240925T193753, end_date=20240925T193754
[2024-09-25T19:37:54.790+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task scrape (Bash command failed. The command returned a non-zero exit code 1.; 68)
[2024-09-25T19:37:54.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:37:54.837+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:37:54.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
