[2024-09-25T19:29:13.988+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:29:13.999+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:29:13.121393+00:00 [queued]>
[2024-09-25T19:29:14.002+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:29:13.121393+00:00 [queued]>
[2024-09-25T19:29:14.003+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:29:14.009+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 19:29:13.121393+00:00
[2024-09-25T19:29:14.013+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:29:14.014+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2024-09-25T19:29:14.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T19:29:13.121393+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp2181676s']
[2024-09-25T19:29:14.019+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask scrape
[2024-09-25T19:29:14.051+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:29:13.121393+00:00 [running]> on host 8445e15c9faf
[2024-09-25T19:29:14.094+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T19:29:13.121393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T19:29:13.121393+00:00'
[2024-09-25T19:29:14.095+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:29:14.102+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:29:14.104+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T19:29:14.110+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:29:14.551+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-25T19:29:14.551+0000] {subprocess.py:93} INFO -   File "/opt/***/tasks/flightDataWebScrape.py", line 4, in <module>
[2024-09-25T19:29:14.553+0000] {subprocess.py:93} INFO -     from tqdm import tqdm
[2024-09-25T19:29:14.555+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'tqdm'
[2024-09-25T19:29:14.568+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-25T19:29:14.569+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:29:14.575+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-25T19:29:14.578+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=AirCrashInvestigation_pipeline, task_id=scrape, execution_date=20240925T192913, start_date=20240925T192913, end_date=20240925T192914
[2024-09-25T19:29:14.590+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task scrape (Bash command failed. The command returned a non-zero exit code 1.; 194)
[2024-09-25T19:29:14.604+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-25T19:29:14.614+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T19:29:14.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
