[2024-09-30T03:47:05.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-30T03:47:05.419+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-30T03:44:12.950745+00:00 [queued]>
[2024-09-30T03:47:05.423+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-30T03:44:12.950745+00:00 [queued]>
[2024-09-30T03:47:05.423+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-30T03:47:05.429+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): loadRedshift> on 2024-09-30 03:44:12.950745+00:00
[2024-09-30T03:47:05.431+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=637) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T03:47:05.432+0000] {standard_task_runner.py:63} INFO - Started process 638 to run task
[2024-09-30T03:47:05.432+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'loadRedshift', 'manual__2024-09-30T03:44:12.950745+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpcwrn1n9u']
[2024-09-30T03:47:05.434+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask loadRedshift
[2024-09-30T03:47:05.456+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-30T03:44:12.950745+00:00 [running]> on host 60abf2d32f6d
[2024-09-30T03:47:05.491+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='loadRedshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T03:44:12.950745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T03:44:12.950745+00:00'
[2024-09-30T03:47:05.492+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-30T03:47:05.498+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-30T03:47:05.498+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/loadRedshift.py']
[2024-09-30T03:47:05.502+0000] {subprocess.py:86} INFO - Output:
[2024-09-30T03:47:06.603+0000] {subprocess.py:93} INFO - Error: connection to server at "flightanalysis-cluster.cd2xqxmrn0kc.us-east-1.redshift.amazonaws.com" (184.73.159.46), port 5439 failed: FATAL:  password authentication failed for user "awsuser"
[2024-09-30T03:47:06.604+0000] {subprocess.py:93} INFO - connection to server at "flightanalysis-cluster.cd2xqxmrn0kc.us-east-1.redshift.amazonaws.com" (184.73.159.46), port 5439 failed: FATAL:  password authentication failed for user "awsuser"
[2024-09-30T03:47:06.604+0000] {subprocess.py:93} INFO - 
[2024-09-30T03:47:06.630+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-30T03:47:06.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-30T03:47:06.644+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=loadRedshift, execution_date=20240930T034412, start_date=20240930T034705, end_date=20240930T034706
[2024-09-30T03:47:06.655+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-30T03:47:06.665+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T03:47:06.666+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
