[2024-09-29T02:57:26.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T02:57:26.383+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-29T02:55:21.359736+00:00 [queued]>
[2024-09-29T02:57:26.387+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-29T02:55:21.359736+00:00 [queued]>
[2024-09-29T02:57:26.387+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-29T02:57:26.393+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): loadRedshift> on 2024-09-29 02:55:21.359736+00:00
[2024-09-29T02:57:26.396+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-29T02:57:26.397+0000] {standard_task_runner.py:63} INFO - Started process 214 to run task
[2024-09-29T02:57:26.397+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'loadRedshift', 'manual__2024-09-29T02:55:21.359736+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpb8yj_q15']
[2024-09-29T02:57:26.399+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask loadRedshift
[2024-09-29T02:57:26.424+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.loadRedshift manual__2024-09-29T02:55:21.359736+00:00 [running]> on host 2e7d9707a826
[2024-09-29T02:57:26.464+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='loadRedshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T02:55:21.359736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T02:55:21.359736+00:00'
[2024-09-29T02:57:26.464+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T02:57:26.471+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:57:26.471+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/loadRedshift.py']
[2024-09-29T02:57:26.476+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:57:28.168+0000] {subprocess.py:93} INFO - Connected to Redshift
[2024-09-29T02:57:28.171+0000] {subprocess.py:93} INFO - Data loaded successfully!
[2024-09-29T02:57:28.172+0000] {subprocess.py:93} INFO - Redshift connection closed
[2024-09-29T02:57:28.211+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T02:57:28.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T02:57:28.227+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=AirCrashInvestigation_pipeline, task_id=loadRedshift, execution_date=20240929T025521, start_date=20240929T025726, end_date=20240929T025728
[2024-09-29T02:57:28.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T02:57:28.253+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T02:57:28.254+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
